/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flink11.java11.springboot.k8s.aliyun.exmaple;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'flink11.java11.springboot.k8s.aliyun.exmaple.greeting' plugin.
 */
public class Flink11Java11SpringbootK8sAliyunExmaplePluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("flink11.java11.springboot.k8s.aliyun.exmaple.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
