/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flink11.java11.springboot.k8s.aliyun.exmaple;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class Flink11Java11SpringbootK8sAliyunExmaplePlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("greeting", task -> {
            task.doLast(s -> System.out.println("Hello from plugin 'flink11.java11.springboot.k8s.aliyun.exmaple.greeting'"));
        });
    }
}
